"""Generate a dashboard YAML for the GivEnergy Local integration."""

from __future__ import annotations

import textwrap

import yaml

# Increment whenever the generated YAML layout changes in a meaningful way.
# __init__.py compares this against the last-generated version stored in HA's
# persistent Store and raises a Repairs issue when they diverge.
DASHBOARD_VERSION = 6


class _NoAliasDumper(yaml.SafeDumper):
    """Expand repeated nodes inline rather than emitting YAML anchors/aliases.

    The Battery Health view reuses the same colour and JS-filter strings across
    dozens of series; without this, PyYAML would replace the repeats with ``*id``
    references — valid YAML, but unreadable in a file users may inspect or edit.
    """

    def ignore_aliases(self, data: object) -> bool:
        return True


# Battery Health palettes. Pack-identity colours (voltage + SoC traces) avoid
# the red/amber of the danger bands and the teal/purple of the temperature
# traces; the temperature palette is parallel (one hue per pack) so a pack's
# temperature reads as a distinct metric from its voltage. Indexed modulo length
# so 7+ packs cycle rather than crash.
_PACK_COLOURS = ("#1e88e5", "#fb8c00", "#43a047", "#6d4c41", "#3949ab", "#c0ca33")
_TEMP_COLOURS = ("#00897b", "#8e24aa", "#d81b60", "#00838f", "#7cb342", "#5e35b1")

# Reject physically-impossible single-sample reads (dongle garbage, see
# givenergy-modbus#78) so a stray 0 V / 6.5 V / 0 °C spike becomes a gap instead
# of wrecking the fixed y-scale. A debounced alert is the real fix; this is the
# chart-readability stopgap until the library filters them upstream.
# parseFloat (not Number) is deliberate: Number(null) and Number('') are 0,
# which is *inside* the temp/power ranges, so a blank/unknown state would plot a
# spurious 0; parseFloat yields NaN for those and falls through to a gap.
_VOLT_FILTER = "const v = parseFloat(x); return (!isNaN(v) && v > 2.0 && v < 4.0) ? v : null;"
_TEMP_FILTER = "const v = parseFloat(x); return (!isNaN(v) && v > -40 && v < 100) ? v : null;"
_POWER_FILTER = "const v = parseFloat(x); return (!isNaN(v) && v > -20000 && v < 20000) ? v : null;"

# The BMS samples one thermistor per 4-cell group.
_TEMP_GROUPS = ((1, 4), (5, 8), (9, 12), (13, 16))


def _health_annotations() -> list[dict]:
    """LFP warn bands, shared by the voltage (left) and temperature (right) axes.

    The right axis is scaled so 3.00 V <-> 10 °C and 3.50 V <-> 45 °C coincide,
    so the single amber band is meaningful for both metrics at once.
    """
    amber = "#f9a825"

    def warn_line(y: float, text: str) -> dict:
        return {
            "y": y,
            "borderColor": amber,
            "strokeDashArray": 0,
            "label": {
                "text": text,
                "position": "left",
                "textAnchor": "start",
                "borderColor": amber,
                "style": {"color": "#000", "background": amber},
            },
        }

    return [
        {"y": 3.5, "y2": 3.6, "fillColor": amber, "opacity": 0.14},
        {"y": 2.9, "y2": 3.0, "fillColor": amber, "opacity": 0.14},
        warn_line(3.5, "warn · 3.50 V / 45 °C"),
        warn_line(3.0, "warn · 3.00 V / 10 °C"),
    ]


def generate_dashboard(
    inv: str, bats: list[str], max_power_kw: int = 10, *, is_ems: bool = False
) -> str:
    """Return a complete Lovelace dashboard YAML string.

    Args:
        inv:           Inverter (or EMS controller) serial number (lowercase).
        bats:          Battery serial number(s) (lowercase).
        max_power_kw:  Vertical envelope (±kW) applied to the Overview power chart's
                       y-axis. Defaults to 10 kW — suitable for single-phase hybrid
                       and AC-coupled inverters. Raise for larger 3-phase systems.
        is_ems:        True when generating for an EMS plant controller. An EMS has no
                       PV/battery/grid/load sensors or inverter controls, so the
                       inverter-centric views would render blank — instead emit a
                       tailored view set (EMS scheduling controls + integration health).
    """
    if is_ems:
        views = "\n".join([_ems_controls_view(inv), _ems_diagnostics_view(inv)])
    else:
        views = "\n".join(
            [
                _overview_view(inv, max_power_kw),
                _energy_view(inv),
                _battery_view(bats),
                # Skip the cross-pack health view on inverter-only installs — the
                # heatmap card rejects an empty battery list.
                *([_battery_health_view(inv, bats)] if bats else []),
                _controls_view(inv),
                _diagnostics_view(inv, max_power_kw),
            ]
        )
    if is_ems:
        return (
            f"# Generated by GivEnergy Local — givenergy_local.generate_dashboard\n"
            f"# Dashboard schema : v{DASHBOARD_VERSION}\n"
            f"# EMS controller   : {inv}\n"
            f"#\n"
            f"# An EMS plant exposes scheduling controls + poll health only — the\n"
            f"# inverter views live on each inverter's own dashboard.\n"
            f"\n"
            f"title: GivEnergy EMS\n"
            f"views:\n"
            f"\n"
            f"{views}\n"
        )
    return (
        f"# Generated by GivEnergy Local — givenergy_local.generate_dashboard\n"
        f"# Dashboard schema : v{DASHBOARD_VERSION}\n"
        f"# Inverter         : {inv}\n"
        f"# Batteries        : {', '.join(bats)}\n"
        f"# Power y-axis     : ±{max_power_kw} kW (Overview chart)\n"
        f"#\n"
        f"# Required custom cards (install via HACS → Frontend):\n"
        f"#   - power-flow-card-plus  (flixlix/power-flow-card-plus)\n"
        f"#   - apexcharts-card  (RomRider/apexcharts-card)\n"
        f"# The Battery Health view's cell-balance heatmap (custom:ge-cell-heatmap) is\n"
        f"# bundled with this integration and served automatically — no install needed.\n"
        f"\n"
        f"title: GivEnergy\n"
        f"views:\n"
        f"\n"
        f"{views}\n"
    )


# ── view builders ─────────────────────────────────────────────────────────────


def _overview_view(inv: str, max_power_kw: int) -> str:
    cap = max_power_kw * 1000
    return f"""\
  # ── Overview ──────────────────────────────────────────────────────────────
  - title: Overview
    path: overview
    icon: mdi:solar-power-variant

    cards:
      - type: custom:power-flow-card-plus
        entities:
          solar:
            entity: {_i(inv, "pv_power")}
            display_zero_state: true
          battery:
            entity: {_i(inv, "battery_power")}
            state_of_charge: {_i(inv, "battery_soc")}
          grid:
            entity: {_i(inv, "grid_export_power")}
          home:
            entity: {_i(inv, "load_power")}

      - type: glance
        title: Status
        columns: 4
        entities:
          - entity: {_i(inv, "status")}
            name: Inverter
          - entity: {_i(inv, "battery_soc")}
            name: Battery SOC
          - entity: select.givenergy_inverter_{inv}_battery_pause_mode
            name: Pause Mode
          - entity: {_i(inv, "battery_temperature")}
            name: Battery Temp

      - type: glance
        title: Today
        columns: 6
        entities:
          - entity: {_i(inv, "pv_energy_today")}
            name: PV
          - entity: {_i(inv, "battery_charge_today")}
            name: Charged
          - entity: {_i(inv, "battery_discharge_today")}
            name: Discharged
          - entity: {_i(inv, "grid_import_today")}
            name: Imported
          - entity: {_i(inv, "grid_export_today")}
            name: Exported
          - entity: {_i(inv, "house_consumption_today")}
            name: Consumed

      - type: custom:apexcharts-card
        header:
          show: true
          title: Power — Last 24 Hours
        graph_span: 24h
        # Clamp to the system's physical envelope. Anything outside is treated as
        # garbage data — the inverter occasionally returns spurious values that
        # would otherwise destroy the chart's auto-scale and make the day unreadable.
        yaxis:
          - min: -{cap}
            max: {cap}
        series:
          - entity: {_i(inv, "pv_power")}
            name: PV
            color: "#FFB300"
          - entity: {_i(inv, "battery_power")}
            name: Battery
            color: "#42A5F5"
          - entity: {_i(inv, "grid_export_power")}
            name: Grid
            color: "#66BB6A"
          - entity: {_i(inv, "load_power")}
            name: Load
            color: "#EF5350"
"""


def _energy_view(inv: str) -> str:
    def col_series(entity: str, name: str, color: str) -> str:
        return (
            f"          - entity: {entity}\n"
            f"            name: {name}\n"
            f'            color: "{color}"\n'
            f"            type: column\n"
            f"            statistics:\n"
            f"              type: state\n"
            f"              period: hour\n"
            f"            group_by:\n"
            f"              func: max\n"
            f"              duration: 1d"
        )

    return f"""\
  # ── Energy ────────────────────────────────────────────────────────────────
  - title: Energy
    path: energy
    icon: mdi:lightning-bolt

    cards:
      - type: custom:apexcharts-card
        header:
          show: true
          title: Daily Generation vs Consumption — Last 30 Days
        graph_span: 30d
        series:
{col_series(_i(inv, "pv_energy_today"), "PV Generated", "#FFB300")}
{col_series(_i(inv, "house_consumption_today"), "Consumed", "#EF5350")}

      - type: custom:apexcharts-card
        header:
          show: true
          title: Grid Import vs Export — Last 30 Days
        graph_span: 30d
        series:
{col_series(_i(inv, "grid_export_today"), "Exported", "#66BB6A")}
{col_series(_i(inv, "grid_import_today"), "Imported", "#EF5350")}

      - type: custom:apexcharts-card
        header:
          show: true
          title: Battery Charge vs Discharge — Last 30 Days
        graph_span: 30d
        series:
{col_series(_i(inv, "battery_charge_today"), "Charged", "#42A5F5")}
{col_series(_i(inv, "battery_discharge_today"), "Discharged", "#7E57C2")}

      - type: entities
        title: All-Time Totals
        entities:
          - entity: {_i(inv, "pv_energy_total")}
            name: PV Generated
          - entity: {_i(inv, "battery_throughput_total")}
            name: Battery Throughput
          - entity: {_i(inv, "grid_export_total")}
            name: Grid Exported
          - entity: {_i(inv, "grid_import_total")}
            name: Grid Imported
          - entity: {_i(inv, "inverter_output_total")}
            name: Inverter Output
          - entity: {_i(inv, "charge_from_grid_total")}
            name: Charged from Grid
          - entity: {_i(inv, "battery_discharge_this_year")}
            name: Discharged This Year
"""


def _battery_view(bats: list[str]) -> str:
    sections = "\n".join(_battery_section(s) for s in bats)
    return f"""\
  # ── Battery ───────────────────────────────────────────────────────────────
  - title: Batteries
    path: battery
    type: sections
    icon: mdi:battery-high

    sections:
{sections}"""


def _battery_section(serial: str) -> str:
    pack = _bat_entity_rows(
        serial,
        [
            ("soc", "SOC"),
            ("voltage", "Voltage"),
            ("temperature_max", "Temp Max"),
            ("temperature_min", "Temp Min"),
            ("bms_mosfet_temperature", "BMS MOSFET Temp"),
            None,
            ("charge_cycles", "Charge Cycles"),
            ("remaining_capacity", "Remaining Capacity"),
            ("calibrated_capacity", "Calibrated Capacity"),
            ("design_capacity", "Design Capacity"),
            ("cell_voltages_sum", "Cell Voltages Sum"),
            ("cell_count", "Cell Count"),
        ],
    )
    temps = _bat_entity_rows(
        serial,
        [
            ("cells_1_4_temperature", "Cells 1-4"),
            ("cells_5_8_temperature", "Cells 5-8"),
            ("cells_9_12_temperature", "Cells 9-12"),
            ("cells_13_16_temperature", "Cells 13-16"),
        ],
    )
    diagnostics = _bat_entity_rows(
        serial,
        [
            ("bms_firmware_version", "BMS Firmware"),
            ("usb_device", "USB Device"),
            ("design_capacity_alt", "Design Capacity Alt"),
            None,
            *((f"bms_status_{i}", f"Status {i}") for i in range(1, 8)),
            None,
            ("bms_warning_1", "Warning 1"),
            ("bms_warning_2", "Warning 2"),
        ],
    )

    return f"""\
      # ── {serial.upper()} ──
      - cards:
          - type: gauge
            entity: {_b(serial, "soc")}
            name: {serial.upper()}
            min: 0
            max: 100
            needle: true
            severity:
              red: 0
              yellow: 20
              green: 40

          - type: entities
            title: Pack Details
            entities:
{pack}

          - type: entities
            title: Cell Temperatures
            entities:
{temps}

          - type: entities
            title: BMS Diagnostics
            entities:
{diagnostics}
"""


def _battery_health_view(inv: str, bats: list[str]) -> str:
    """Plant-level cell diagnostics: balance heatmap + cell/temp & power/SoC charts.

    Cross-pack by nature (the heatmap and line charts span every pack), so this
    is its own ``sections`` view rather than per-battery sections. It depends on
    the bundled ``custom:ge-cell-heatmap`` card (served automatically by this
    integration) plus ``apexcharts-card``. Each card is given full width via
    ``grid_options`` since the time-series read best wide.

    Built as Python dicts and serialised with PyYAML — the apexcharts cards carry
    40+ series with quoting-sensitive JS transforms, which hand-written YAML
    f-strings would mangle.
    """
    volt_series: list[dict] = []
    temp_series: list[dict] = []
    soc_series: list[dict] = []
    for index, serial in enumerate(bats):
        # Pack ordinal (B1, B2, ...) keeps labels unique and matches the heatmap's
        # 1..N pack numbering; serials are too long for tooltips and collide when
        # packs share a model prefix.
        tag = f"B{index + 1}"
        pack_colour = _PACK_COLOURS[index % len(_PACK_COLOURS)]
        temp_colour = _TEMP_COLOURS[index % len(_TEMP_COLOURS)]
        for cell in range(1, 17):
            volt_series.append(
                {
                    "entity": f"sensor.givenergy_battery_{serial}_cell_{cell}_voltage",
                    "name": f"{tag} {cell}",
                    "color": pack_colour,
                    "stroke_width": 1,
                    "yaxis_id": "v",
                    "transform": _VOLT_FILTER,
                }
            )
        for lo, hi in _TEMP_GROUPS:
            temp_series.append(
                {
                    "entity": f"sensor.givenergy_battery_{serial}_cells_{lo}_{hi}_temperature",
                    "name": f"{tag} T{lo}-{hi}",
                    "color": temp_colour,
                    "stroke_width": 1,
                    "yaxis_id": "temp",
                    "transform": _TEMP_FILTER,
                }
            )
        soc_series.append(
            {
                "entity": f"sensor.givenergy_battery_{serial}_soc",
                "name": f"{tag} SoC",
                "color": pack_colour,
                "stroke_width": 1,
                "yaxis_id": "soc",
            }
        )

    note = {
        "type": "markdown",
        "content": (
            "## Battery health\n"
            "Cross-pack cell diagnostics. **Heatmap**: each cell coloured by its "
            "mV deviation from its own pack's mean (imbalance shows at any charge "
            "level). **Cell voltages + temperatures**: every cell (left) with "
            "cell-group temperatures (right) on a shared warn band. **Power + "
            "SoC**: the charge/discharge rate driving each pack's state of charge. "
            "Implausible single-sample reads are filtered to gaps."
        ),
    }
    heatmap = {
        "type": "custom:ge-cell-heatmap",
        "title": "Cell balance — deviation from pack mean",
        "batteries": list(bats),
    }
    cell_chart = {
        "type": "custom:apexcharts-card",
        "header": {
            "show": True,
            "title": (
                "Cell voltages (left, V) + cell-group temps (right, °C — warn bands shared) — 24h"
            ),
        },
        "graph_span": "24h",
        "chart_type": "line",
        "yaxis": [
            {"id": "v", "min": 2.9, "max": 3.6, "decimals": 2},
            {"id": "temp", "opposite": True, "min": 3, "max": 52, "decimals": 0},
        ],
        "apex_config": {
            "legend": {"show": False},
            "annotations": {"yaxis": _health_annotations()},
            "chart": {"height": 330},
        },
        "series": volt_series + temp_series,
    }
    power_chart = {
        "type": "custom:apexcharts-card",
        "header": {
            "show": True,
            "title": "Battery power (left, W, 2-min avg) + pack SoC (right) — 24h",
        },
        "graph_span": "24h",
        "chart_type": "line",
        "apex_config": {
            "legend": {"show": False},
            "annotations": {
                "yaxis": [
                    {
                        "y": 0,
                        "borderColor": "#616161",
                        "strokeDashArray": 3,
                        "label": {
                            "text": "0 W (idle)",
                            "position": "left",
                            "textAnchor": "start",
                            "style": {"color": "#000", "background": "#e0e0e0"},
                        },
                    }
                ]
            },
            "chart": {"height": 330},
        },
        "series": [
            {
                "entity": f"sensor.givenergy_inverter_{inv}_battery_power",
                "name": "Battery power",
                "color": "#8e24aa",
                "stroke_width": 1,
                "transform": _POWER_FILTER,
                "yaxis_id": "w",
                "group_by": {"duration": "2m", "func": "avg"},
            },
            *soc_series,
        ],
        "yaxis": [
            {"id": "w", "decimals": 0},
            {"id": "soc", "opposite": True, "min": 0, "max": 100, "decimals": 0},
        ],
    }

    cards: list[dict] = [note, heatmap, cell_chart, power_chart]
    for card in cards:
        card["grid_options"] = {"columns": "full"}

    view = {
        "title": "Battery Health",
        "path": "battery-health",
        "type": "sections",
        "icon": "mdi:heart-pulse",
        "sections": [{"type": "grid", "cards": cards}],
    }

    body = yaml.dump(
        [view],
        Dumper=_NoAliasDumper,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        indent=2,
        width=10**9,
    )
    header = "  # ── Battery Health ──────────────────────────────────────────────────────────\n"
    return header + textwrap.indent(body, "  ").rstrip("\n")


def _controls_view(inv: str) -> str:
    return f"""\
  # ── Controls ──────────────────────────────────────────────────────────────
  - title: Controls
    path: controls
    icon: mdi:tune

    cards:
      - type: entities
        title: Mode
        entities:
          - entity: select.givenergy_inverter_{inv}_battery_power_mode
            name: Battery Power Mode
          - entity: select.givenergy_inverter_{inv}_battery_pause_mode
            name: Pause Mode
          - entity: {_i(inv, "battery_calibration_stage")}
            name: Calibration Stage

      - type: entities
        title: Charging
        entities:
          - entity: switch.givenergy_inverter_{inv}_enable_charge
            name: Enable Charge
          - entity: number.givenergy_inverter_{inv}_charge_target_soc
            name: Charge Target SOC
          - entity: number.givenergy_inverter_{inv}_battery_soc_reserve
            name: SOC Reserve
          - entity: number.givenergy_inverter_{inv}_battery_charge_limit
            name: Charge Power Limit
          - type: divider
          - entity: time.givenergy_inverter_{inv}_charge_slot_1_start
            name: Slot 1 Start
          - entity: time.givenergy_inverter_{inv}_charge_slot_1_end
            name: Slot 1 End
          - entity: time.givenergy_inverter_{inv}_charge_slot_2_start
            name: Slot 2 Start
          - entity: time.givenergy_inverter_{inv}_charge_slot_2_end
            name: Slot 2 End

      - type: entities
        title: Discharging
        entities:
          - entity: switch.givenergy_inverter_{inv}_enable_discharge
            name: Enable Discharge
          - entity: number.givenergy_inverter_{inv}_battery_discharge_limit
            name: Discharge Power Limit
          - entity: number.givenergy_inverter_{inv}_battery_discharge_min_power_reserve
            name: Min Power Reserve
          - type: divider
          - entity: time.givenergy_inverter_{inv}_discharge_slot_1_start
            name: Slot 1 Start
          - entity: time.givenergy_inverter_{inv}_discharge_slot_1_end
            name: Slot 1 End
          - entity: time.givenergy_inverter_{inv}_discharge_slot_2_start
            name: Slot 2 Start
          - entity: time.givenergy_inverter_{inv}_discharge_slot_2_end
            name: Slot 2 End
"""


def _integration_health_card(inv: str, kind: str = "inverter") -> str:
    """The coordinator-level poll-health card — applies to any plant (incl. EMS).

    `kind` is the device-name noun in the entity_id prefix ("inverter" / "ems"),
    matching the device naming in sensor._device_kind.
    """
    p = f"sensor.givenergy_{kind}_{inv}"
    return f"""\
      - type: entities
        title: Integration Health
        entities:
          - entity: {p}_last_successful_refresh
            name: Last Successful Refresh
          - entity: {p}_consecutive_refresh_failures
            name: Consecutive Failures
          - entity: {p}_partial_refresh_failures
            name: Partial Failures
          - entity: {p}_total_refresh_failures
            name: Total Failures"""


def _diagnostics_view(inv: str, max_power_kw: int) -> str:
    return f"""\
  # ── Diagnostics ───────────────────────────────────────────────────────────
  - title: Diagnostics
    path: diagnostics
    icon: mdi:wrench

    cards:
{_integration_health_card(inv)}

      - type: entities
        title: Faults & Warnings
        entities:
          - entity: {_i(inv, "status")}
            name: Inverter Status
          - entity: {_i(inv, "fault_code")}
            name: Fault Code
          - entity: {_i(inv, "fault_messages")}
            name: Fault Messages
          - entity: {_i(inv, "inverter_errors")}
            name: Inverter Errors
          - entity: {_i(inv, "charger_warning_code")}
            name: Charger Warning Code
          - entity: {_i(inv, "charge_status")}
            name: Charge Status (raw)
          - entity: {_i(inv, "system_mode")}
            name: System Mode (raw)

      - type: entities
        title: Temperatures
        entities:
          - entity: {_i(inv, "battery_temperature")}
            name: Battery
          - entity: {_i(inv, "inverter_heatsink_temperature")}
            name: Inverter Heatsink
          - entity: {_i(inv, "charger_temperature")}
            name: Charger

      - type: entities
        title: Electrical
        entities:
          - entity: {_i(inv, "ac_voltage")}
            name: AC Voltage
          - entity: {_i(inv, "ac_frequency")}
            name: AC Frequency
          - entity: {_i(inv, "battery_voltage")}
            name: Battery Voltage
          - entity: {_i(inv, "battery_current")}
            name: Battery Current
          - entity: {_i(inv, "grid_port_current")}
            name: Grid Port Current
          - entity: {_i(inv, "positive_dc_bus_voltage")}
            name: Positive DC Bus
          - entity: {_i(inv, "negative_dc_bus_voltage")}
            name: Negative DC Bus
          - entity: {_i(inv, "grid_apparent_power")}
            name: Grid Apparent Power
          - entity: {_i(inv, "inverter_power_factor")}
            name: Inverter Power Factor

      - type: entities
        title: PV Strings
        entities:
          - entity: {_i(inv, "pv_string_1_voltage")}
            name: String 1 Voltage
          - entity: {_i(inv, "pv_string_1_current")}
            name: String 1 Current
          - entity: {_i(inv, "pv_string_1_power")}
            name: String 1 Power
          - entity: {_i(inv, "pv_string_2_voltage")}
            name: String 2 Voltage
          - entity: {_i(inv, "pv_string_2_current")}
            name: String 2 Current
          - entity: {_i(inv, "pv_string_2_power")}
            name: String 2 Power

      - type: entities
        title: Hardware & Firmware
        entities:
          - entity: {_i(inv, "arm_firmware_version")}
            name: ARM Firmware
          - entity: {_i(inv, "dsp_firmware_version")}
            name: DSP Firmware
          - entity: {_i(inv, "modbus_version")}
            name: Modbus Version
          - entity: {_i(inv, "work_time_total")}
            name: Work Time
          - entity: {_i(inv, "device_type_code")}
            name: Device Type Code
          - entity: {_i(inv, "mppt_count")}
            name: MPPT Count
          - entity: {_i(inv, "phase_count")}
            name: Phase Count
          - entity: {_i(inv, "battery_type")}
            name: Battery Type
          - entity: {_i(inv, "meter_type")}
            name: Meter Type
          - entity: {_i(inv, "usb_device")}
            name: USB Device
          - entity: {_i(inv, "battery_nominal_capacity")}
            name: Nominal Capacity (kWh)
          - entity: {_i(inv, "battery_capacity")}
            name: Capacity (Ah)

      - type: entities
        title: Integration
        entities:
          - type: button
            name: Regenerate Dashboard
            icon: mdi:view-dashboard-refresh
            action_name: Run
            tap_action:
              action: perform-action
              perform_action: givenergy_local.generate_dashboard
              data:
                max_power_kw: {max_power_kw}
          - type: button
            name: Capture Debug Frames (60 s)
            icon: mdi:bug-outline
            action_name: Run
            tap_action:
              action: perform-action
              perform_action: givenergy_local.capture_frames
              data:
                duration: 60
"""


# ── EMS plant views ────────────────────────────────────────────────────────────
#
# An EMS controller has no PV/battery/grid/load sensors and none of the inverter
# controls, so its dashboard is a tailored pair (scheduling controls + integration
# health) rather than the inverter view set.
#
# Entity ids use the `givenergy_ems_{serial}_…` prefix: the EMS device is named
# "GivEnergy EMS {serial}" (sensor.py `_device_kind`), so its entities slug to
# `givenergy_ems_…`. Existing installs realign via HA's "Recreate entity IDs" action
# (prompted on upgrade); fresh installs derive these ids from the start.
#
# Note the slug is from the entity *name*: the per-slot SOC number is named
# "EMS … Slot N Target SOC", so its slug is `ems_{kind}_slot_{n}_target_soc` (not `key`).


def _ems_slot_card(inv: str, kind: str, title: str) -> str:
    rows: list[str] = []
    for idx in (1, 2, 3):
        if idx > 1:
            rows.append("          - type: divider")
        rows += [
            f"          - entity: time.givenergy_ems_{inv}_ems_{kind}_slot_{idx}_start",
            f"            name: Slot {idx} Start",
            f"          - entity: time.givenergy_ems_{inv}_ems_{kind}_slot_{idx}_end",
            f"            name: Slot {idx} End",
            f"          - entity: number.givenergy_ems_{inv}_ems_{kind}_slot_{idx}_target_soc",
            f"            name: Slot {idx} Target SOC",
        ]
    body = "\n".join(rows)
    return f"""\
      - type: entities
        title: {title}
        entities:
{body}"""


def _ems_controls_view(inv: str) -> str:
    slot_cards = "\n".join(
        _ems_slot_card(inv, kind, title)
        for kind, title in (
            ("charge", "Charge Slots"),
            ("discharge", "Discharge Slots"),
            ("export", "Export Slots"),
        )
    )
    return f"""\
  # ── EMS Controls ──────────────────────────────────────────────────────────
  - title: EMS Controls
    path: ems-controls
    icon: mdi:tune

    cards:
      - type: entities
        title: Plant
        entities:
          - entity: switch.givenergy_ems_{inv}_flexi_ems_control
            name: Flexi EMS Control
{slot_cards}
"""


def _ems_diagnostics_view(inv: str) -> str:
    return f"""\
  # ── Diagnostics ───────────────────────────────────────────────────────────
  - title: Diagnostics
    path: diagnostics
    icon: mdi:wrench

    cards:
{_integration_health_card(inv, "ems")}
"""


# ── helpers ───────────────────────────────────────────────────────────────────


def _i(serial: str, key: str) -> str:
    return f"sensor.givenergy_inverter_{serial}_{key}"


def _b(serial: str, key: str) -> str:
    return f"sensor.givenergy_battery_{serial}_{key}"


def _bat_entity_rows(serial: str, items: list[tuple[str, str] | None]) -> str:
    lines: list[str] = []
    for item in items:
        if item is None:
            lines.append("              - type: divider")
        else:
            key, name = item
            lines.append(f"              - entity: {_b(serial, key)}")
            lines.append(f"                name: {name}")
    return "\n".join(lines)
